"""
lexicon.py — Curated Wurm Online vocabulary for token extraction.
Used by the enrichment functions in lenses.py to power word clouds
and frequency analyses.
"""

# ─── ENCHANTS ────────────────────────────────────────────────────────────────
# Abbreviations and full names for all relevant priest enchants.
ENCHANTS = {
    # Channeling enchants
    "coc":          "Circle of Cunning",
    "circle of cunning": "Circle of Cunning",
    "woa":          "Wind of Ages",
    "wind of ages": "Wind of Ages",
    "botd":         "Blessing of the Dark",
    "blessing of the dark": "Blessing of the Dark",
    "nimbleness":   "Nimbleness",
    "lt":           "Life Transfer",
    "life transfer": "Life Transfer",
    "ms":           "Mind Stealer",
    "mind stealer": "Mind Stealer",
    "fa":           "Flaming Aura",
    "flaming aura": "Flaming Aura",
    "fb":           "Frostbrand",
    "frostbrand":   "Frostbrand",
    "venom":        "Venom",
    "aos":          "Aura of Shared Pain",
    "aura of shared pain": "Aura of Shared Pain",
    "rt":           "Rotting Touch",
    "rotting touch": "Rotting Touch",
    "ad":           "Animal's Demise",
    "animal's demise": "Animal's Demise",
    "ho":           "Hunt of the Ancients",
    "hunt of the ancients": "Hunt of the Ancients",
    "smeagain":     "Smite",
    "smite":        "Smite",
    "opulence":     "Opulence",
    "courier":      "Courier",
    "lurker":       "Lurker in the Deep",
    "lurker in the deep": "Lurker in the Deep",
    "blessings":    "Blessings of the Dark",
    "oakshell":     "Oakshell",
    "mole":         "Eyes of the Mole",
    "eyes of the mole": "Eyes of the Mole",
    "fr":           "Fire Protection",
    "fire protection": "Fire Protection",
    "fp":           "Frost Protection",
    "frost protection": "Frost Protection",
    "acid protection": "Acid Protection",
    "cr":           "Cold Resistance",
    "sr":           "Spirit Resistance",
    "hr":           "Holy Resistance",
    "dr":           "Dark Resistance",
    "web armour":   "Web Armour",
    "web armor":    "Web Armour",
    "gl":           "Genesis",
    "genesis":      "Genesis",
    "wi":           "Winter's Grasp",
    "winter's grasp": "Winter's Grasp",
    "dominate":     "Dominate",
    "charm":        "Charm",
    "scorn":        "Scorn of Libila",
    "scorn of libila": "Scorn of Libila",
}

# Canonical display names for deduplication
ENCHANT_CANONICAL = {v: v for v in ENCHANTS.values()}

# ─── PROFESSIONS / SKILLS ────────────────────────────────────────────────────
PROFESSIONS = {
    "smithing":         "Smithing",
    "weaponsmithing":   "Smithing",
    "armoursmithing":   "Smithing",
    "armorsmithing":    "Smithing",
    "blacksmithing":    "Smithing",
    "cooking":          "Cooking",
    "baking":           "Cooking",
    "tailoring":        "Tailoring",
    "leatherworking":   "Leatherworking",
    "carpentry":        "Carpentry",
    "fine carpentry":   "Carpentry",
    "masonry":          "Masonry",
    "stonecutting":     "Masonry",
    "mining":           "Mining",
    "digging":          "Digging",
    "channeling":       "Channeling",
    "priest":           "Channeling",
    "casting":          "Channeling",
    "farming":          "Farming",
    "gardening":        "Farming",
    "animal husbandry": "Animal Husbandry",
    "breeding":         "Animal Husbandry",
    "fishing":          "Fishing",
    "forestry":         "Forestry",
    "woodcutting":      "Forestry",
    "bowery":           "Bowery",
    "fletching":        "Bowery",
    "jewelry":          "Jewelry",
    "jewelsmithing":    "Jewelry",
    "shipbuilding":     "Shipbuilding",
    "bowyery":          "Bowery",
    "ropemaking":       "Ropemaking",
    "cloth tailoring":  "Tailoring",
    "papyrusmaking":    "Papyrusmaking",
    "winemaking":       "Winemaking",
    "pottery":          "Pottery",
    "thatching":        "Thatching",
    "butchering":       "Butchering",
    "soul depth":       "Channeling",
}

# ─── ITEMS (curated, most common in Wurm trade) ──────────────────────────────
# Format: lowercase alias → canonical display name
ITEMS = {
    # Metals & raw mats
    "iron ore":         "Iron Ore",
    "iron":             "Iron",
    "steel":            "Steel",
    "copper":           "Copper",
    "tin":              "Tin",
    "zinc":             "Zinc",
    "lead":             "Lead",
    "gold":             "Gold",
    "silver":           "Silver",
    "electrum":         "Electrum",
    "adamantine":       "Adamantine",
    "glimmersteel":     "Glimmersteel",
    "seryll":           "Seryll",
    "moon metal":       "Moon Metal",
    "ore":              "Ore",
    "ingot":            "Ingot",
    "lump":             "Lump",
    "bsb":              "Bulk Storage Bin",
    "crate":            "Crate",
    "bulk storage":     "Bulk Storage Bin",
    # Wood
    "log":              "Logs",
    "logs":             "Logs",
    "plank":            "Planks",
    "planks":           "Planks",
    "shaft":            "Shaft",
    "peg":              "Peg",
    "kindling":         "Kindling",
    "wood":             "Wood",
    "cedar":            "Cedar",
    "willow":           "Willow",
    "oak":              "Oak",
    "pine":             "Pine",
    "birch":            "Birch",
    "maple":            "Maple",
    "walnut":           "Walnut",
    "cherry":           "Cherry",
    "spruce":           "Spruce",
    "chestnut":         "Chestnut",
    # Cloth & hides
    "wool":             "Wool",
    "cotton":           "Cotton",
    "leather":          "Leather",
    "hide":             "Hide",
    "cordage":          "Cordage Rope",
    "rope":             "Rope",
    "cloth":            "Cloth",
    "string":           "String",
    # Stone
    "stone":            "Stone Brick",
    "stone brick":      "Stone Brick",
    "marble":           "Marble",
    "slate":            "Slate",
    "sandstone":        "Sandstone",
    "pottery":          "Pottery Shards",
    "clay":             "Clay",
    "mortar":           "Mortar",
    # Tools
    "hammer":           "Hammer",
    "large anvil":      "Large Anvil",
    "small anvil":      "Small Anvil",
    "anvil":            "Anvil",
    "saw":              "Saw",
    "file":             "File",
    "awl":              "Awl",
    "needle":           "Needle",
    "trowel":           "Trowel",
    "pickaxe":          "Pickaxe",
    "shovel":           "Shovel",
    "rake":             "Rake",
    "rope tool":        "Rope Tool",
    "grindstone":       "Grindstone",
    "whetstone":        "Whetstone",
    "spatula":          "Spatula",
    "carving knife":    "Carving Knife",
    "chisel":           "Chisel",
    "scissors":         "Scissors",
    "stone chisel":     "Stone Chisel",
    "fruit press":      "Fruit Press",
    "leatherworking knife": "Leatherworking Knife",
    "clay shaper":      "Clay Shaper",
    "pottery wheel":    "Pottery Wheel",
    # Weapons
    "sword":            "Sword",
    "longsword":        "Longsword",
    "short sword":      "Short Sword",
    "two-handed sword": "Two-Handed Sword",
    "huge axe":         "Huge Axe",
    "hatchet":          "Hatchet",
    "axe":              "Axe",
    "spear":            "Spear",
    "bow":              "Bow",
    "longbow":          "Longbow",
    "mace":             "Mace",
    "maul":             "Maul",
    "large maul":       "Large Maul",
    "staff":            "Staff",
    "morning star":     "Morning Star",
    "war hammer":       "War Hammer",
    "scythe":           "Scythe",
    "sickle":           "Sickle",
    "sling":            "Sling",
    "club":             "Club",
    # Armour
    "plate":            "Plate Armour",
    "plate armour":     "Plate Armour",
    "plate armor":      "Plate Armour",
    "chain":            "Chain Armour",
    "chain armour":     "Chain Armour",
    "studded":          "Studded Armour",
    "leather armour":   "Leather Armour",
    "helm":             "Helm",
    "helmet":           "Helmet",
    "shield":           "Shield",
    "large shield":     "Large Shield",
    "medium shield":    "Medium Shield",
    "small shield":     "Small Shield",
    "gauntlet":         "Gauntlet",
    "boot":             "Boots",
    "greave":           "Greave",
    "vambrace":         "Vambrace",
    "jacket":           "Jacket",
    "pants":            "Pants",
    "sleeves":          "Sleeves",
    "gloves":           "Gloves",
    # Consumables
    "sleep powder":     "Sleep Powder",
    "healing cover":    "Healing Cover",
    "bandage":          "Bandage",
    "cotton bandage":   "Bandage",
    "potion":           "Potion",
    "jar":              "Jar",
    "ointment":         "Ointment",
    "salve":            "Salve",
    # Animals
    "horse":            "Horse",
    "hell horse":       "Hell Horse",
    "bison":            "Bison",
    "bull":             "Bull",
    "cow":              "Cow",
    "pig":              "Pig",
    "sheep":            "Sheep",
    "chicken":          "Chicken",
    "drake":            "Drake",
    "aged":             "Aged Animal",
    "venerable":        "Venerable Animal",
    # Boats & vehicles
    "boat":             "Boat",
    "sailboat":         "Sailboat",
    "rowboat":          "Rowboat",
    "corbita":          "Corbita",
    "knarr":            "Knarr",
    "cog":              "Cog",
    "caravel":          "Caravel",
    "wagon":            "Wagon",
    "cart":             "Cart",
    "large cart":       "Large Cart",
    "catamaran":        "Catamaran",
    # Magic / priest
    "rune":             "Rune",
    "gem":              "Gem",
    "statuette":        "Statuette",
    "scroll":           "Scroll",
    "totem":            "Totem",
    "source crystal":   "Source Crystal",
    "source salt":      "Source Salt",
    "blood":            "Dragon Blood",
    # Food
    "meal":             "Meal",
    "bread":            "Bread",
    "pizza":            "Pizza",
    "casserole":        "Casserole",
    "stew":             "Stew",
    "soup":             "Soup",
    "sausage":          "Sausage",
    "cheese":           "Cheese",
    "wine":             "Wine",
    "beer":             "Beer",
    "ale":              "Ale",
    "fruit":            "Fruit",
    # Housing / deeds
    "deed":             "Deed",
    "settlement":       "Deed",
    "house":            "House",
    "floor":            "Floor",
    "wall":             "Wall",
    "fence":            "Fence",
    "bridge":           "Bridge",
    "column":           "Column",
    "arch":             "Arch",
    "guard tower":      "Guard Tower",
    "tower":            "Guard Tower",
    # Misc
    "key":              "Key",
    "saddle":           "Saddle",
    "saddlebag":        "Saddlebag",
    "pelt":             "Pelt",
    "skull":            "Skull",
    "trophy":           "Trophy",
    "scale":            "Dragon Scale",
    "dragon scale":     "Dragon Scale",
    "journal":          "Journal",
    "tome":             "Tome",
    "backpack":         "Backpack",
    "toolbelt":         "Toolbelt",
    "lantern":          "Lantern",
    "lamp":             "Lamp",
    "anchor":           "Anchor",
    "chart":            "Nautical Chart",
    "nautical chart":   "Nautical Chart",
}

# ─── SERVICES ────────────────────────────────────────────────────────────────
SERVICES = {
    "imp":          "Improving",
    "imping":       "Improving",
    "improve":      "Improving",
    "improving":    "Improving",
    "enchant":      "Enchanting",
    "enchanting":   "Enchanting",
    "cast":         "Enchanting",
    "casting":      "Enchanting",
    "courier":      "Courier Enchant",
    "delivery":     "Delivery",
    "transport":    "Transport",
    "taxi":         "Transport",
    "ferry":        "Transport",
    "deed":         "Deed Service",
    "deed service": "Deed Service",
    "guard tower":  "Guard Tower Construction",
    "terraform":    "Terraforming",
    "terraforming": "Terraforming",
    "flatten":      "Terraforming",
    "leveling":     "Terraforming",
    "digging":      "Terraforming",
    "highway":      "Highway Construction",
    "road":         "Highway Construction",
    "bridge":       "Bridge Construction",
    "butchering":   "Butchering",
    "butcher":      "Butchering",
    "tracking":     "Tracking",
    "guide":        "Guide Service",
    "escorting":    "Guide Service",
    "training":     "Training",
    "skill training": "Training",
    "alliance":     "Alliance",
    "hire":         "Hiring",
    "hiring":       "Hiring",
}

# ─── STOPWORDS (noise to filter from free tokenization) ──────────────────────
STOPWORDS = {
    "wtb", "wts", "wtt", "pm", "me", "pls", "please", "need", "looking",
    "selling", "buying", "have", "want", "any", "all", "and", "the", "for",
    "with", "from", "cod", "can", "are", "not", "or", "in", "on", "at",
    "hi", "hey", "hello", "message", "msg", "offer", "offers", "price",
    "prices", "cheap", "bulk", "good", "great", "nice", "quality", "ql",
    "dm", "send", "also", "more", "some", "lot", "lots", "many", "few",
    "new", "old", "best", "fast", "quick", "asap", "sold", "sale", "free",
    "stock", "available", "avail", "trade", "open", "closed", "done",
    "thanks", "thank", "cheers", "paid", "pay", "will", "wont", "can",
}
