import pathlib

path = pathlib.Path('pipeline/gui.py')
text = path.read_text('utf-8')

replacements = {
    'Wurm Market Observatory — local pipeline tool': 'Wurm Market Observatory — ferramenta de pipeline local',
    '  Merge  ': '  Mesclar  ',
    '  Calibrate  ': '  Calibrar  ',
    '  Settings  ': '  Configurações  ',
    '  Run  ': '  Executar  ',
    
    'Restored corpus (.txt)': 'Corpus restaurado (.txt)',
    'Browse…': 'Procurar…',
    '↳  Scan Corpus': '↳  Analisar Corpus',
    'Period': 'Período',
    'Log lines parsed': 'Linhas de log lidas',
    'Days found': 'Dias encontrados',
    'Coverage': 'Cobertura',
    'Gaps detected': 'Gaps (falhas) detectados',
    'Servers observed': 'Servidores observados',
    'Detected gaps:': 'Gaps detectados:',
    'Select restored Wurm corpus': 'Selecione o corpus restaurado do Wurm',
    'Text files': 'Arquivos de texto',
    'All files': 'Todos os arquivos',
    'Please select a valid .txt file first.': 'Por favor, selecione um arquivo .txt válido primeiro.',
    'Scanning corpus…': 'Analisando corpus…',
    'No gaps detected — full coverage.': 'Nenhum gap detectado — cobertura total.',
    'Corpus scanned. Ready to run.': 'Corpus analisado. Pronto para executar.',
    '"Error"': '"Erro"',
    'Scan Error': 'Erro na Análise',
    'Unexpected error:\\n\\n': 'Erro inesperado:\\n\\n',
    
    'Select multiple .txt files to merge into one corpus before analysis.': 'Selecione vários arquivos .txt para mesclar em um único corpus antes da análise.',
    'Duplicates by day are removed. Files are merged chronologically.': 'Duplicatas por dia são removidas. Os arquivos são mesclados em ordem cronológica.',
    'Add Files…': 'Adicionar Arquivos…',
    'Clear List': 'Limpar Lista',
    'Save merged file as:': 'Salvar arquivo mesclado como:',
    '⊕  Merge & Load into Corpus tab': '⊕  Mesclar e Carregar na aba Corpus',
    'Select Wurm .txt corpus files': 'Selecione os arquivos .txt do corpus do Wurm',
    'Save merged corpus as…': 'Salvar corpus mesclado como…',
    'Add at least one .txt file to merge.': 'Adicione pelo menos um arquivo .txt para mesclar.',
    'Choose where to save the merged file.': 'Escolha onde salvar o arquivo mesclado.',
    'Merging…': 'Mesclando…',
    'Merging files…': 'Mesclando arquivos…',
    '✓ Merged {n_files} files · {n_days} days · saved to {Path(merged_path).name}': '✓ Mesclou {n_files} arquivos · {n_days} dias · salvo em {Path(merged_path).name}',
    'Merge complete. Go to Corpus tab and click Scan Corpus.': 'Mesclagem concluída. Vá para a aba Corpus e clique em Analisar Corpus.',
    'Merge complete': 'Mesclagem concluída',
    '{n_files} files merged into {n_days} unique days.\\nFile loaded into Corpus tab — click \\'Scan Corpus\\' to analyse.': '{n_files} arquivos mesclados em {n_days} dias únicos.\\nArquivo carregado na aba Corpus — clique em \\'Analisar Corpus\\' para verificar.',
    'Merge Error': 'Erro na Mesclagem',
    
    'Paste a few lines of your real .txt here to verify the parser reads them correctly.': 'Cole algumas linhas do seu .txt real aqui para verificar se o sistema lê corretamente.',
    'The parser expects: [HH:MM:SS] <PlayerName> (ServerName) message text': 'O sistema espera o formato: [HH:MM:SS] <NomeDoJogador> (NomeDoServidor) texto da mensagem',
    '↳  Parse & Inspect': '↳  Analisar e Inspecionar',
    '─── Parse Result ───': '─── Resultado da Análise ───',
    '  Raw lines read:  ': '  Linhas brutas lidas: ',
    '  Lines parsed OK: ': '  Linhas lidas OK:     ',
    '  Lines skipped:   ': '  Linhas ignoradas:    ',
    '  Days found:      ': '  Dias encontrados:    ',
    '  Servers:         ': '  Servidores:          ',
    '─── First 5 parsed lines ───': '─── Primeiras 5 linhas interpretadas ───',
    '… and {len(result.lines)-5} more lines.': '… e mais {len(result.lines)-5} linhas.',
    '⚠ No lines parsed. Check the format matches:': '⚠ Nenhuma linha interpretada. Verifique se o formato bate:',
    'If your logs use a different format, paste 5–10 real lines': 'Se seus logs usam um formato diferente, cole de 5 a 10 linhas reais',
    'and share them so the parser can be adjusted.': 'e compartilhe para que o leitor possa ser ajustado.',
    
    '"Output"': '"Saída"',
    'Observatory data path': 'Caminho de dados do Observatory',
    'Server (SFI / NFI)': 'Servidor (SFI / NFI)',
    'Cleaning Rules': 'Regras de Limpeza',
    'WTS keywords (comma-separated)': 'Palavras-chave WTS (separadas por vírgula)',
    'WTB keywords (comma-separated)': 'Palavras-chave WTB (separadas por vírgula)',
    'Min message length': 'Tamanho mínimo da mensagem',
    'Lenses to Generate': 'Lentes (Filtros) para Gerar',
    'Seller Activity': 'Atividade de Vendedores',
    'Buyer Activity': 'Atividade de Compradores',
    'Top sellers to show': 'Top vendedores para mostrar',
    'Minimum mentions': 'Mínimo de menções',
    'Item Categories  (edit config.json for full control)': 'Categorias de Itens  (edite o config.json para controle total)',
    'Save Settings': 'Salvar Configurações',
    'Settings saved.': 'Configurações salvas.',
    '"Saved"': '"Salvo"',
    'Settings saved to config.json': 'Configurações salvas no config.json',
    
    'Generate JSON datasets from scanned corpus.': 'Gerar arquivos JSON a partir do corpus analisado.',
    '▶  Run Pipeline': '▶  Executar Pipeline',
    'Log:': 'Log de execução:',
    'Go to the Corpus tab and scan a file first.': 'Vá para a aba Corpus e analise um arquivo primeiro.',
    'No corpus': 'Nenhum corpus',
    'Running pipeline…': 'Executando pipeline…',
    '─── Corpus Workbench Pipeline ───': '─── Pipeline Corpus Workbench ───',
    'Generating corpus-meta.json…': 'Gerando corpus-meta.json…',
    '  ✓ corpus-meta.json written': '  ✓ corpus-meta.json gravado',
    'Generating seller-activity.json…': 'Gerando seller-activity.json…',
    '  ✓ seller-activity.json written': '  ✓ seller-activity.json gravado',
    '    Unique sellers:  ': '    Vendedores únicos: ',
    '    Total mentions:  ': '    Total de menções:  ',
    '    Top category:    ': '    Top categoria:     ',
    '    Top seller:      ': '    Top vendedor:      ',
    'Generating buyer-activity.json…': 'Gerando buyer-activity.json…',
    '  ✓ buyer-activity.json written': '  ✓ buyer-activity.json gravado',
    '    Unique buyers:   ': '    Compradores únicos:',
    '─── Pipeline complete ───────────────': '─── Pipeline concluído ───────────────',
    '  Files written to: ': '  Arquivos salvos em: ',
    '  Reload your Observatory dev server to see real data.': '  Recarregue o dev server do Observatory para ver os dados reais.',
    'Done. JSON datasets ready.': 'Concluído. Arquivos JSON prontos.',
    
    '"Ready."': '"Pronto."',
    'No network · No database · Local only': 'Sem internet · Sem banco de dados · Apenas local',
    '(skipped: ': '(ignoradas: ',
    'of': 'de'
}

for k, v in replacements.items():
    text = text.replace(k, v)

path.write_text(text, 'utf-8')
print('Translation applied.')
